table Attendance
	lineageTag: a14cdf0e-78b7-4ba9-822c-7019f161d160

	measure 'Count of AttendanceStatus for Present' =
			
			CALCULATE(
				COUNTA('Attendance'[AttendanceStatus]),
				'Attendance'[AttendanceStatus] IN { "Present" }
			)
		formatString: 0
		lineageTag: 5571ec0f-0009-4293-84a8-876dc0548290

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "FilteredMeasure"
				}

		changedProperty = FormatString

	column AttendanceID
		dataType: int64
		formatString: 0
		lineageTag: 35db35ee-f401-4bf0-8cbf-c9d33e443b04
		summarizeBy: count
		sourceColumn: AttendanceID

		annotation SummarizationSetBy = Automatic

	column EmployeeID
		dataType: int64
		formatString: 0
		lineageTag: d4333125-f822-4f1d-baf6-2b61d58b62ae
		summarizeBy: none
		sourceColumn: EmployeeID

		annotation SummarizationSetBy = Automatic

	column CheckInTime
		dataType: dateTime
		formatString: Long Time
		lineageTag: 544d2d8e-492f-4a8b-bd15-825191042d6d
		summarizeBy: none
		sourceColumn: CheckInTime

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column CheckOutTime
		dataType: dateTime
		formatString: Long Time
		lineageTag: 8eebdd09-f199-43ba-8b14-3ff0103b6447
		summarizeBy: none
		sourceColumn: CheckOutTime

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column ScheduledStartTime
		dataType: dateTime
		formatString: Long Time
		lineageTag: 35909079-da1f-47e8-b67c-0a2a5d58d6f6
		summarizeBy: none
		sourceColumn: ScheduledStartTime

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column ScheduledEndTime
		dataType: dateTime
		formatString: Long Time
		lineageTag: 5b10d246-8a49-4a78-ae91-a16e98ae718d
		summarizeBy: none
		sourceColumn: ScheduledEndTime

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column TotalHoursWorked
		dataType: double
		lineageTag: 33586c0a-4d2f-4585-aced-1d6e14ccc7e6
		summarizeBy: sum
		sourceColumn: TotalHoursWorked

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column OvertimeHours
		dataType: double
		lineageTag: b6357d45-b85b-4023-93f0-f93bba3604dd
		summarizeBy: sum
		sourceColumn: OvertimeHours

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column AttendanceStatus
		dataType: string
		lineageTag: 8f79b73c-c212-45f8-997a-61d91228e696
		summarizeBy: none
		sourceColumn: AttendanceStatus

		annotation SummarizationSetBy = Automatic

	column LateArrivalFlag
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: cd35a604-4566-4ad3-95e3-d042cca11520
		summarizeBy: none
		sourceColumn: LateArrivalFlag

		annotation SummarizationSetBy = Automatic

	column EarlyLogoutFlag
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 0d8049b2-a1ba-4d89-b70f-b25750de53cc
		summarizeBy: none
		sourceColumn: EarlyLogoutFlag

		annotation SummarizationSetBy = Automatic

	column LeaveType
		dataType: string
		lineageTag: fc918320-3c6b-4221-bdbe-43e29efe38c7
		summarizeBy: none
		sourceColumn: LeaveType

		annotation SummarizationSetBy = Automatic

	column WorkMode
		dataType: string
		lineageTag: a4691073-f929-43f4-8a97-d9c82d820db4
		summarizeBy: none
		sourceColumn: WorkMode

		annotation SummarizationSetBy = Automatic

	column ProductivityScore
		dataType: double
		lineageTag: e285a1b7-54f7-4a9d-93cf-cf1edc8436d1
		summarizeBy: sum
		sourceColumn: ProductivityScore

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TaskCountCompleted
		dataType: int64
		formatString: 0
		lineageTag: fc9cd4fb-df1e-4a25-b210-0afa9c32b0b0
		summarizeBy: sum
		sourceColumn: TaskCountCompleted

		annotation SummarizationSetBy = Automatic

	column TargetTaskCount
		dataType: int64
		formatString: 0
		lineageTag: f17d45ae-2f92-489f-8130-9e3c6d8f9f20
		summarizeBy: sum
		sourceColumn: TargetTaskCount

		annotation SummarizationSetBy = Automatic

	column BillableHours
		dataType: double
		lineageTag: ad06a8f1-cead-4823-a5d0-c883a13e319a
		summarizeBy: sum
		sourceColumn: BillableHours

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NonBillableHours
		dataType: double
		lineageTag: 7f04c1a0-aa1f-4b3c-8d83-1ab24273429d
		summarizeBy: sum
		sourceColumn: NonBillableHours

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4f09ea67-802a-4016-8aa4-74243a87f809
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 8dbc5e37-ec8e-4456-b545-950a739a5d88
			defaultHierarchy: LocalDateTable_9cc64efc-3d67-47a6-929e-71b31bc93655.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition Attendance = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\MohammedAbrar\Desktop\consmini\attendance.xlsx"), null, true),
				    Attendance_Sheet = Source{[Item="Attendance",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Attendance_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"AttendanceID", Int64.Type}, {"EmployeeID", Int64.Type}, {"Date", type date}, {"CheckInTime", type time}, {"CheckOutTime", type time}, {"ScheduledStartTime", type time}, {"ScheduledEndTime", type time}, {"TotalHoursWorked", type number}, {"OvertimeHours", type number}, {"AttendanceStatus", type text}, {"LateArrivalFlag", type logical}, {"EarlyLogoutFlag", type logical}, {"LeaveType", type text}, {"WorkMode", type text}, {"ProductivityScore", type number}, {"TaskCountCompleted", Int64.Type}, {"TargetTaskCount", Int64.Type}, {"BillableHours", type number}, {"NonBillableHours", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

